files:
  - source: /app/Language/en/*.php
    translation: /app/Language/%two_letters_code%/%original_file_name%
  - source: /modules/**/Language/en/*.php
    translation: /modules/**/Language/%two_letters_code%/%original_file_name%
