stages:
  - build

docker-build-rolling:
  stage: build
  image:
    name: docker.io/docker:23.0.3-dind
  services:
    - docker:23.0.3-dind
  variables:
    TAG: $CI_COMMIT_BRANCH
  script:
    - mkdir -p /root/.docker
    - cp ${DOCKER_HUB_CONFIG} /root/.docker/config.json
    - docker buildx build --push --platform=linux/amd64,linux/arm64 --file=docker/production/web-server/Dockerfile --tag=${DOCKER_IMAGE_WEB_SERVER}:${TAG} .
    - docker buildx build --push --platform=linux/amd64,linux/arm64 --file=docker/production/app/Dockerfile --tag=${DOCKER_IMAGE_APP}:${TAG} .
    - docker buildx build --push --platform=linux/amd64,linux/arm64 --file=docker/production/video-clipper/Dockerfile --tag=${DOCKER_IMAGE_VIDEO_CLIPPER}:${TAG} .
    - docker buildx build --push --platform=linux/amd64,linux/arm64 --file=docker/production/unit/Dockerfile --tag=${DOCKER_IMAGE_UNIT}:${TAG} .
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: bundle
  only:
    refs:
      - develop

docker-build-main-release:
  stage: build
  image:
    name: docker.io/docker:23.0.3-dind
  services:
    - docker:23.0.3-dind
  script:
    - mkdir -p /root/.docker
    - cp ${DOCKER_HUB_CONFIG} /root/.docker/config.json
    - export CP_VERSION=$(cat CP_VERSION.env)
    - docker buildx build --push --platform=linux/amd64,linux/arm64 --file=docker/production/web-server/Dockerfile --tag=${DOCKER_IMAGE_WEB_SERVER}:${CP_VERSION} --tag={DOCKER_IMAGE_WEB_SERVER}:latest .
    - docker buildx build --push --platform=linux/amd64,linux/arm64 --file=docker/production/app/Dockerfile --tag=${DOCKER_IMAGE_APP}:${CP_VERSION} --tag=${DOCKER_IMAGE_APP}:latest .
    - docker buildx build --push --platform=linux/amd64,linux/arm64 --file=docker/production/video-clipper/Dockerfile --tag=${DOCKER_IMAGE_VIDEO_CLIPPER}:${CP_VERSION} --tag=${DOCKER_IMAGE_VIDEO_CLIPPER}:latest .
    - docker buildx build --push --platform=linux/amd64,linux/arm64 --file=docker/production/unit/Dockerfile --tag=${DOCKER_IMAGE_UNIT}:${CP_VERSION} --tag=${DOCKER_IMAGE_UNIT}:latest .
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: release
  only:
    refs:
      - main

docker-build-alpha-beta-release:
  stage: build
  image:
    name: docker.io/docker:23.0.3-dind
  services:
    - docker:23.0.3-dind
  variables:
    TAG: $CI_COMMIT_BRANCH
  script:
    - mkdir -p /root/.docker
    - cp ${DOCKER_HUB_CONFIG} /root/.docker/config.json
    - export CP_VERSION=$(cat CP_VERSION.env)
    - docker buildx build --push --platform=linux/amd64,linux/arm64 --file=docker/production/web-server/Dockerfile --tag=${DOCKER_IMAGE_WEB_SERVER}:${CP_VERSION} --tag={DOCKER_IMAGE_WEB_SERVER}:${TAG} .
    - docker buildx build --push --platform=linux/amd64,linux/arm64 --file=docker/production/app/Dockerfile --tag=${DOCKER_IMAGE_APP}:${CP_VERSION} --tag=${DOCKER_IMAGE_APP}:${TAG} .
    - docker buildx build --push --platform=linux/amd64,linux/arm64 --file=docker/production/video-clipper/Dockerfile --tag=${DOCKER_IMAGE_VIDEO_CLIPPER}:${CP_VERSION} --tag=${DOCKER_IMAGE_VIDEO_CLIPPER}:${TAG} .
    - docker buildx build --push --platform=linux/amd64,linux/arm64 --file=docker/production/unit/Dockerfile --tag=${DOCKER_IMAGE_UNIT}:${CP_VERSION} --tag=${DOCKER_IMAGE_UNIT}:${TAG} .
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: release
  only:
    refs:
      - alpha
      - beta
